apiVersion: v1
kind: Service
metadata:
  name: ai-agent
  labels:
    app: ai-agent
spec:
  type: ClusterIP
  selector:
    app: ai-agent
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
